apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tt-backend-replicaset
  labels:
    app: testotester
    tier: backend
    environment: dev
  #namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testotester
  template:
    metadata:
      name: tt-backend-pod
      labels: 
        tier: backend
    spec:
      containers:
      - image: karolpawlak/tt-server
        name: tt-server-container
      - image: karolpawlak/tt-client
        name: tt-client-container