apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tt-server-pod
  name: tt-server-pod
spec:
  containers:
  - image: karolpawlak/tt-server
    name: tt-server-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}