apiVersion: v1
kind: Pod
metadata:
  labels:
    app: testotester
    tier: backend
    environment: dev
  name: tt-server-pod
  #namespace: dev
spec:
  containers:
  - image: karolpawlak/tt-server
    name: tt-server-container
  restartPolicy: Never